name: Cron Bot

on:
  schedule:
    - cron: '0 */4 * * *'   # සෑම පැය 4කට වරක්
  workflow_dispatch:         # Manual run සඳහා

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 350     # පැය 5.5ක් (6h limit එකට යන්න කලින් නවත්වන්න)
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm start
